# Generated by Django 3.2 on 2022-05-18 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20220518_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='from_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
